/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.Funcionario;

import DAO.FuncionarioDAO;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author tayna
 */
public class TelaEditarFuncionario extends javax.swing.JFrame {

    public static void recebeId(Funcionario func){
        txtCodFunc.setText(String.valueOf(func.getId()));
        txtCodFunc.requestFocus();
    }
    /**
     * Creates new form TelaEditarFuncionario
     */
    public TelaEditarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonSairFun = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeFunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCPFfunc = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTelefFunc = new javax.swing.JFormattedTextField();
        labelEmail = new javax.swing.JLabel();
        txtEmailFunc = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        cBoxTipoFunc = new javax.swing.JComboBox<>();
        labelEsp = new javax.swing.JLabel();
        especialidadeEdtFunc = new javax.swing.JTextField();
        SalvarEdtFunc = new javax.swing.JButton();
        CancelarEdtFunc = new javax.swing.JButton();
        txtCodFunc = new javax.swing.JTextField();
        labelCodigoFunc = new javax.swing.JLabel();
        buttonPesqFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionário - Tela de Edição");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tayna\\Google Drive\\GRADUAÇÃO\\6º Período\\Oficina de Integração 2\\4Life\\imagens\\icons\\doctor.png")); // NOI18N
        jLabel1.setText("EDITAR FUNCIONÁRIO");

        buttonSairFun.setBackground(new java.awt.Color(0, 51, 51));
        buttonSairFun.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSairFun.setForeground(new java.awt.Color(255, 255, 255));
        buttonSairFun.setText("Sair");
        buttonSairFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairFunActionPerformed(evt);
            }
        });

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setText("Nome:");

        txtNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF:");

        try {
            txtCPFfunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFfuncActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        try {
            campoTelefFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefFuncActionPerformed(evt);
            }
        });

        labelEmail.setText("Email:");

        labelTipo.setText("Tipo:");

        cBoxTipoFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione um tipo", "administrador", "médico", "enfermeiro", "secretária", "recepcionista", "auxiliar de enfermagem" }));
        cBoxTipoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoFuncActionPerformed(evt);
            }
        });

        labelEsp.setText("Especialidade:");

        SalvarEdtFunc.setBackground(new java.awt.Color(0, 102, 52));
        SalvarEdtFunc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        SalvarEdtFunc.setForeground(new java.awt.Color(255, 255, 255));
        SalvarEdtFunc.setText("Salvar");
        SalvarEdtFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarEdtFuncActionPerformed(evt);
            }
        });

        CancelarEdtFunc.setBackground(new java.awt.Color(211, 0, 0));
        CancelarEdtFunc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        CancelarEdtFunc.setForeground(new java.awt.Color(255, 255, 255));
        CancelarEdtFunc.setText("Cancelar");
        CancelarEdtFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEdtFuncActionPerformed(evt);
            }
        });

        labelCodigoFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCodigoFunc.setText("Código:");

        buttonPesqFunc.setBackground(new java.awt.Color(0, 102, 52));
        buttonPesqFunc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonPesqFunc.setForeground(new java.awt.Color(255, 255, 255));
        buttonPesqFunc.setIcon(new javax.swing.ImageIcon("C:\\Users\\tayna\\Google Drive\\GRADUAÇÃO\\6º Período\\Oficina de Integração 2\\4Life\\imagens\\icons\\search.png")); // NOI18N
        buttonPesqFunc.setText("Pesquisar");
        buttonPesqFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesqFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SalvarEdtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CancelarEdtFunc))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 13, Short.MAX_VALUE)
                                        .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cBoxTipoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelEsp))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCPFfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTelefFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(especialidadeEdtFunc)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCodigoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPesqFunc))
                            .addComponent(txtNomeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addComponent(txtEmailFunc))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesqFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxTipoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialidadeEdtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarEdtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarEdtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSairFun, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSairFun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        setBounds(250, 100, 696, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairFunActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonSairFunActionPerformed

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorMoved

    private void buttonPesqFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesqFuncActionPerformed
        Funcionario funcionario = new Funcionario();
        
        if(txtCodFunc.getText().equals("")){  //chama a tela de Busca Paciente quando o campo estiver vazio.
            TelaBuscarFuncionario telaBusca = new TelaBuscarFuncionario();
            telaBusca.setVisible(true);
        }
        else{
            funcionario.setId(Integer.parseInt(txtCodFunc.getText()));
            FuncionarioDAO pdao = new FuncionarioDAO();
            
            try{
                if(pdao.pesquisaFunc(funcionario)){
                    if(funcionario != null){
                        txtNomeFunc.setText(funcionario.getNome().trim());                  
                        txtCPFfunc.setText(funcionario.getCPF().trim());
                        cBoxTipoFunc.setSelectedItem(funcionario.getTipo_func());
                        campoTelefFunc.setText(funcionario.getTelefone().trim());
                        txtEmailFunc.setText(funcionario.getEmail().trim());
                        especialidadeEdtFunc.setText(funcionario.getEspecialidade().trim());
                    }
                }
            }
            catch(Exception exc){
                JOptionPane.showMessageDialog(null, "Erro ao pesquisar funcionário!" +exc);
            }
        }  
    }//GEN-LAST:event_buttonPesqFuncActionPerformed

    private void CancelarEdtFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEdtFuncActionPerformed
        txtCodFunc.setText("");
        txtNomeFunc.setText("");
        txtCPFfunc.setText("");
        cBoxTipoFunc.setSelectedItem("selecione um tipo");
        campoTelefFunc.setText("");
        txtEmailFunc.setText("");
        especialidadeEdtFunc.setText("");
    }//GEN-LAST:event_CancelarEdtFuncActionPerformed

    private void SalvarEdtFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarEdtFuncActionPerformed
        try{
            Funcionario func = new Funcionario();

            func.setNome(txtNomeFunc.getText());
            func.setCPF(txtCPFfunc.getText());
            func.setTipo_func(String.valueOf(cBoxTipoFunc.getSelectedItem()));
            func.setTelefone(campoTelefFunc.getText());
            func.setEmail(txtEmailFunc.getText());
            func.setEspecialidade(especialidadeEdtFunc.getText());
            func.setId(Integer.parseInt(txtCodFunc.getText()));
            

            FuncionarioDAO fdao = new FuncionarioDAO();
            fdao.editar(func);

            JOptionPane.showMessageDialog(null, "Funcionário atualizado com sucesso!");

            // apaga os dados preenchidos nos campos de texto
            txtCodFunc.setText("");
            txtNomeFunc.setText("");
            txtCPFfunc.setText("");
            cBoxTipoFunc.setSelectedItem("selecione um tipo");
            campoTelefFunc.setText("");
            txtEmailFunc.setText("");
            especialidadeEdtFunc.setText("");
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao alterar dados!" + erro);
        }
    }//GEN-LAST:event_SalvarEdtFuncActionPerformed

    private void cBoxTipoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxTipoFuncActionPerformed

    private void campoTelefFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefFuncActionPerformed

    private void txtCPFfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFfuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFfuncActionPerformed

    private void txtNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarEdtFunc;
    private javax.swing.JButton SalvarEdtFunc;
    private javax.swing.JButton buttonPesqFunc;
    private javax.swing.JButton buttonSairFun;
    private javax.swing.JComboBox<String> cBoxTipoFunc;
    private javax.swing.JFormattedTextField campoTelefFunc;
    private javax.swing.JTextField especialidadeEdtFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCodigoFunc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEsp;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JFormattedTextField txtCPFfunc;
    static javax.swing.JTextField txtCodFunc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtNomeFunc;
    // End of variables declaration//GEN-END:variables
}
