/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.PacienteDAO;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Paciente;

/**
 *
 * @author tayna
 */
public class telaPaciente extends javax.swing.JFrame {

    public void listaPaciente(){
        try{
            PacienteDAO dao = new PacienteDAO();
            List<Paciente> pac = dao.listaPac();
            
            DefaultTableModel model = (DefaultTableModel) tabelaPaciente.getModel();
            model.setNumRows(0);
            
            for(Paciente p : pac){
                model.addRow(new Object []{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getData_nascimento(),
                p.getTelefone(),
                p.getCidade(),
                p.getEstado()
            });
            }
            
        }catch(Exception exc){
            
        }
    }
    
    public telaPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastrar = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelCEP = new javax.swing.JLabel();
        labelNum = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        txtNomePac = new javax.swing.JTextField();
        txtCpfPac = new javax.swing.JFormattedTextField();
        txtIdPac = new javax.swing.JTextField();
        txtTelefonePac = new javax.swing.JFormattedTextField();
        txtCepPac = new javax.swing.JFormattedTextField();
        txtNumPac = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        labelDataPac = new javax.swing.JLabel();
        LabelEmailPac = new javax.swing.JLabel();
        LabelRua = new javax.swing.JLabel();
        LabelBairro = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        txtEmailPac = new javax.swing.JTextField();
        txtRuaPac = new javax.swing.JTextField();
        txtBairroPac = new javax.swing.JTextField();
        comboBoxEstado = new javax.swing.JComboBox<>();
        buttonSalvarPac = new javax.swing.JButton();
        buttonCancelarPac = new javax.swing.JButton();
        txtDateNasPac = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelNomePesq = new javax.swing.JLabel();
        txtPesquisaPac = new javax.swing.JTextField();
        buttonPesquisaPac = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPaciente = new javax.swing.JTable();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Paciente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tayna\\Google Drive\\GRADUAÇÃO\\6º Período\\Oficina de Integração 2\\4Life\\imagens\\icons\\team.png")); // NOI18N
        jLabel1.setText("PACIENTE");
        jLabel1.setIconTextGap(5);

        buttonSair.setBackground(new java.awt.Color(0, 51, 51));
        buttonSair.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addComponent(buttonSair))
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 52));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFocusCycleRoot(true);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(131, 69));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(805, 474));

        labelNome.setText("Nome:");

        labelCPF.setText("CPF:");

        labelID.setText("Código:");

        labelTelefone.setText("Telefone:");

        labelCEP.setText("CEP:");

        labelNum.setText("Número:");

        labelCidade.setText("Cidade:");

        try {
            txtCpfPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtIdPac.setEditable(false);

        try {
            txtTelefonePac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCepPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelDataPac.setText("Data de nascimento:");

        LabelEmailPac.setText("Email:");

        LabelRua.setText("Rua:");

        LabelBairro.setText("Bairro:");

        jLabelEstado.setText("Estado:");

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado", "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "DISTRITO FEDERAL", "ESPÍRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS" }));

        buttonSalvarPac.setBackground(new java.awt.Color(0, 102, 52));
        buttonSalvarPac.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonSalvarPac.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalvarPac.setText("Salvar");
        buttonSalvarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarPacActionPerformed(evt);
            }
        });

        buttonCancelarPac.setBackground(new java.awt.Color(211, 0, 0));
        buttonCancelarPac.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonCancelarPac.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelarPac.setText("Cancelar");
        buttonCancelarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarPacActionPerformed(evt);
            }
        });

        try {
            txtDateNasPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadastrarLayout = new javax.swing.GroupLayout(jPanelCadastrar);
        jPanelCadastrar.setLayout(jPanelCadastrarLayout);
        jPanelCadastrarLayout.setHorizontalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSalvarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonCancelarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCidade))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumPac))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCepPac))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefonePac))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdPac))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarLayout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(labelDataPac, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDateNasPac))
                                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                                .addComponent(LabelEmailPac, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtEmailPac))
                                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                                    .addComponent(LabelBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(LabelRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBairroPac)
                                                    .addComponent(comboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtRuaPac))))))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelCadastrarLayout.setVerticalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDataPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDateNasPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmailPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonePac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBairroPac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCidade))
                .addGap(43, 43, 43)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Cadastrar Paciente", jPanelCadastrar);

        jLabelNomePesq.setText("Nome:");

        buttonPesquisaPac.setBackground(new java.awt.Color(0, 102, 52));
        buttonPesquisaPac.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonPesquisaPac.setForeground(new java.awt.Color(255, 255, 255));
        buttonPesquisaPac.setText("Pesquisar");

        tabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME DO PACIENTE", "CPF", "DATA DE NASC.", "TELEFONE", "CIDADE", "ESTADO"
            }
        ));
        tabelaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPaciente);
        if (tabelaPaciente.getColumnModel().getColumnCount() > 0) {
            tabelaPaciente.getColumnModel().getColumn(0).setMaxWidth(190);
            tabelaPaciente.getColumnModel().getColumn(1).setPreferredWidth(190);
        }

        buttonEditar.setBackground(new java.awt.Color(0, 102, 52));
        buttonEditar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonEditar.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setBackground(new java.awt.Color(211, 0, 0));
        buttonExcluir.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        buttonExcluir.setText("Deletar");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelNomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPesquisaPac)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesquisaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Buscar Paciente", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonCancelarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarPacActionPerformed
        txtIdPac.setText("");
        txtNomePac.setText("");
        txtCpfPac.setText("");
        txtEmailPac.setText("");
        txtTelefonePac.setText("");
        txtDateNasPac.setText("");
        txtCepPac.setText("");
        txtRuaPac.setText("");
        txtBairroPac.setText("");
        txtCidade.setText("");
        comboBoxEstado.setSelectedItem("Selecione um estado");
        txtNumPac.setText("");
    }//GEN-LAST:event_buttonCancelarPacActionPerformed

    private void buttonSalvarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarPacActionPerformed
        try{
            Paciente paciente = new Paciente();
            
            paciente.setNome(txtNomePac.getText());
            paciente.setCpf(txtCpfPac.getText());
            paciente.setEmail(txtEmailPac.getText());
            paciente.setTelefone(txtTelefonePac.getText());
            paciente.setData_nascimento(txtDateNasPac.getText());
            paciente.setCep(txtCepPac.getText());
            paciente.setRua(txtRuaPac.getText());
            paciente.setBairro(txtBairroPac.getText());
            paciente.setCidade(txtCidade.getText());
            paciente.setEstado(String.valueOf(comboBoxEstado.getSelectedItem()));
            paciente.setNum_endereco(Integer.parseInt(txtNumPac.getText()));
            
            //validação dos campos
            if((txtNomePac.getText().isEmpty()) || (txtCpfPac.getText().isEmpty()) || (txtEmailPac.getText().isEmpty()) || (txtTelefonePac.getText().isEmpty()) || (txtDateNasPac.getText().isEmpty()) || (txtCepPac.getText().isEmpty()) || (txtRuaPac.getText().isEmpty()) || (txtBairroPac.getText().isEmpty()) || (txtCidade.getText().isEmpty()) || (txtNumPac.getText().isEmpty()) ){
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
            }else{
                PacienteDAO dao = new PacienteDAO();
                dao.cadastrar(paciente);
                
                //insere os valores na tabela
                DefaultTableModel paciet;
                paciet = (DefaultTableModel) tabelaPaciente.getModel();
                Object[] dados = {txtNomePac.getText(),txtCpfPac.getText(),txtDateNasPac.getText(),txtTelefonePac.getText(),txtCidade.getText(),comboBoxEstado.getSelectedItem()};
                paciet.addRow(dados);
            }
            //limpa os campos ao salvar paciente.
            txtIdPac.setText("");
            txtNomePac.setText("");
            txtCpfPac.setText("");
            txtEmailPac.setText("");
            txtTelefonePac.setText("");
            txtDateNasPac.setText("");
            txtCepPac.setText("");
            txtRuaPac.setText("");
            txtBairroPac.setText("");
            txtCidade.setText("");
            comboBoxEstado.setSelectedItem("Selecione um estado");
            txtNumPac.setText("");
            
        }catch(Exception exc){
            JOptionPane.showMessageDialog(null, "ERRO AO SALVAR PACIENTE!" +exc);
        }
    }//GEN-LAST:event_buttonSalvarPacActionPerformed

    private void tabelaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPacienteMouseClicked
        //pega os dados de um paciente na tabela
        txtIdPac.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 0).toString());
        txtNomePac.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 1).toString());
        txtCpfPac.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 2).toString());
        txtDateNasPac.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 3).toString());
        //SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        //txtDateNasPac.setText(sdf.format(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 3).toString()));
        txtTelefonePac.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 4).toString());
        txtCidade.setText(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 5).toString());
        comboBoxEstado.setSelectedItem(tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tabelaPacienteMouseClicked

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja excluir paciente?", "CONFIRMAÇÃO DE EXCLUSÃO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(confirma == JOptionPane.YES_OPTION){
            if(tabelaPaciente.getSelectedRow() != -1){
                Paciente paciente = new Paciente();
                PacienteDAO dao = new PacienteDAO();
                
                paciente.setId((int) tabelaPaciente.getValueAt(tabelaPaciente.getSelectedRow(), 0));
                dao.deletar(paciente);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um paciente para excluir!");
            }
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        try{
            Paciente pac = new Paciente();
            
            pac.setNome(txtNomePac.getText());
            pac.setCpf(txtCpfPac.getText());
            pac.setEmail(txtEmailPac.getText());
            pac.setTelefone(txtTelefonePac.getText());
            pac.setData_nascimento(txtDateNasPac.getText());
            pac.setCep(txtCepPac.getText());
            pac.setRua(txtRuaPac.getText());
            pac.setBairro(txtBairroPac.getText());
            pac.setCidade(txtCidade.getText());
            pac.setEstado(String.valueOf(comboBoxEstado.getSelectedItem()));
            pac.setNum_endereco(Integer.parseInt(txtNumPac.getText()));
            pac.setId(Integer.parseInt(txtIdPac.getText()));
            
            PacienteDAO dao = new PacienteDAO();
            dao.editar(pac);
            
            //insere os dados na tabela
            DefaultTableModel pact;
            pact = (DefaultTableModel) tabelaPaciente.getModel();
            Object[] dados = {txtNomePac.getText(),txtCpfPac.getText(),txtDateNasPac.getText(),txtTelefonePac.getText(),txtCidade.getText(),comboBoxEstado.getSelectedItem()};
            pact.addRow(dados);
            
            JOptionPane.showMessageDialog(null, "Paciente atualizado com sucesso!");
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao alterar dados!" + erro);
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listaPaciente();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelEmailPac;
    private javax.swing.JLabel LabelRua;
    private javax.swing.JButton buttonCancelarPac;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonPesquisaPac;
    private javax.swing.JButton buttonSair;
    private javax.swing.JButton buttonSalvarPac;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNomePesq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCadastrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelDataPac;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNum;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTable tabelaPaciente;
    private javax.swing.JTextField txtBairroPac;
    private javax.swing.JFormattedTextField txtCepPac;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCpfPac;
    private javax.swing.JFormattedTextField txtDateNasPac;
    private javax.swing.JTextField txtEmailPac;
    private javax.swing.JTextField txtIdPac;
    private javax.swing.JTextField txtNomePac;
    private javax.swing.JTextField txtNumPac;
    private javax.swing.JTextField txtPesquisaPac;
    private javax.swing.JTextField txtRuaPac;
    private javax.swing.JFormattedTextField txtTelefonePac;
    // End of variables declaration//GEN-END:variables
}
